export const APP_START = 'APP_START';

export const ADD_WIDGET = 'ADD_WIDGET';
export const UPDATE_WIDGETS_POSITION = 'UPDATE_WIDGETS_POSITION';
export const REMOVE_WIDGET = 'REMOVE_WIDGET';
export const SET_WIDGETS = 'SET_WIDGETS';

export const SAVE_DASHBOARD = 'SAVE_DASHBOARD';
export const SAVE_DASHBOARD_SUCCESS = 'SAVE_DASHBOARD_SUCCESS';
export const SAVE_DASHBOARD_FAILURE = 'SAVE_DASHBOARD_FAILURE';

export const CREATE_DASHBOARD = 'CREATE_DASHBOARD';
export const CREATE_DASHBOARD_SUCCESS = 'CREATE_DASHBOARD_SUCCESS';
export const CREATE_DASHBOARD_FAILURE = 'CREATE_DASHBOARD_FAILURE';

export const GET_DASHBOARDS = 'GET_DASHBOARDS';
export const GET_DASHBOARDS_SUCCESS = 'GET_DASHBOARDS_SUCCESS';
export const GET_DASHBOARDS_FAILURE = 'GET_DASHBOARDS_FAILURE';

export const GET_DASHBOARD_BY_ID = 'GET_DASHBOARD_BY_ID';
export const GET_DASHBOARD_BY_ID_SUCCESS = 'GET_DASHBOARD_BY_ID_SUCCESS';
export const GET_DASHBOARD_BY_ID_FAILURE = 'GET_DASHBOARD_BY_ID_FAILURE';

export const DELETE_DASHBOARD = 'DELETE_DASHBOARD';
export const DELETE_DASHBOARD_SUCCESS = 'DELETE_DASHBOARD_SUCCESS';
export const DELETE_DASHBOARD_FAILURE = 'DELETE_DASHBOARD_FAILURE';

export const DASHBOARD_REDUCER = 'dashboard';
export const WIDGET_REDUCER = 'widget';

export const ROUTES = {
  DASHBOARD: '/dashboard',
  EDIT_DASHBOARD: '/edit/dashboard',
};

export const DASHBOARD_VERSION = '0.0.1';
