export const SET_IS_DRAGGED = 'SET_IS_DRAGGED';
export const SET_COLORS = 'SET_COLORS';
export const SET_ACTIVE_COLOR = 'SET_ACTIVE_COLOR';
export const SET_ADD_COLOR_PICKER_OPEN = 'SET_ADD_COLOR_PICKER_OPEN';
export const SET_COLOR_PICKER_POSITION = 'SET_COLOR_PICKER_POSITION';
