export const data = [
  {
    platform: ['Web', 'Mobile', 'Tablet'],
    referrer: 'google/ads',
    price: 0.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
    number: 'three',
  },
  {
    platform: 'Mobile',
    referrer: 'google/ads',
    price: 0.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
    number: '15',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 1.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
    number: 'one',
  },
  {
    platform: 'Web',
    referrer: 'facebook/cpc',
    price: 0.5,
    province: 'liaoning',
    city: 'Shenyang',
    country: 'china',
    number: 'two',
  },
  {
    platform: 'Web',
    referrer: 'facebook/cpc',
    price: 0.5,
    province: 'liaoning',
    city: 'Shenyang',
    country: 'china',
    number: '1asd',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 0.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
    number: '1',
  },
  {
    platform: 'Mobile',
    referrer: 'google/ads',
    price: 2.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
    number: 'Three',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 0.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
    number: 'Four',
  },
  {
    platform: 'Mobile',
    referrer: 'facebook/cpc',
    price: 10.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
    number: '5',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 0.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
    number: '1two',
  },
  {
    platform: 'Mobile',
    referrer: 'google/ads',
    price: 0.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
    number: '15',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 1.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
    number: 'one',
  },
  {
    platform: 'Web',
    referrer: 'facebook/cpc',
    price: 0.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
    number: '1two',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 0.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
    number: '1two',
  },
  {
    platform: 'Mobile',
    referrer: 'google/ads',
    price: 2.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
    number: '1two',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 0.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
    number: 'three',
  },
  {
    platform: 'Mobile',
    referrer: 'facebook/cpc',
    price: 10.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
    number: '1',
  },
];
