export const data = [
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 0.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
  },
  {
    platform: 'Mobile',
    referrer: 'google/ads',
    price: 0.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 1.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
  },
  {
    platform: 'Web',
    referrer: 'facebook/cpc',
    price: 0.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 0.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
  },
  {
    platform: 'Mobile',
    referrer: 'google/ads',
    price: 2.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 0.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
  },
  {
    platform: 'Mobile',
    referrer: 'facebook/cpc',
    price: 10.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 0.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
  },
  {
    platform: 'Mobile',
    referrer: 'google/ads',
    price: 0.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 1.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
  },
  {
    platform: 'Web',
    referrer: 'facebook/cpc',
    price: 0.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 0.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
  },
  {
    platform: 'Mobile',
    referrer: 'google/ads',
    price: 2.5,
    province: 'Liaoning',
    city: 'Shenyang',
    country: 'China',
  },
  {
    platform: 'Web',
    referrer: 'google/ads',
    price: 0.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
  },
  {
    platform: 'Mobile',
    referrer: 'facebook/cpc',
    price: 10.5,
    province: 'West Virginia',
    city: 'Parsons',
    country: 'United States',
  },
];
