export const theme = {
  colors: {
    black: '#1d2729',
  },
  fontSizes: [
    '10px',
    '12px',
    '14px',
    '16px',
    '18px',
    '20px',
    '24px',
    '30px',
    '36px',
    '48px',
    '60px',
    '72px',
  ],
  lineHeights: [
    '12px',
    '14px',
    '16px',
    '20px',
    '22px',
    '24px',
    '34px',
    '36px',
    '40px',
    '50px',
    '64px',
  ],
  fontWeights: {
    normal: 'normal',
    bold: 'bold',
  },
  fontStyles: {
    normal: 'normal',
    italic: 'italic',
  },
  textOption: {
    none: {},
    h1: {
      fontFamily: 'Gangster Grotesk Bold',
      fontSize: '36px',
      lineHeight: '40px',
    },
    h2: {
      fontFamily: 'Gangster Grotesk Bold',
      fontSize: '30px',
      lineHeight: '34px',
    },
    h3: {
      fontFamily: 'Gangster Grotesk Regular',
      fontSize: '20px',
      lineHeight: '22px',
    },
    h4: {
      fontFamily: 'Lato Regular',
      fontWeight: 'normal',
      fontSize: '16px',
      lineHeight: '20px',
    },
    h5: {
      fontFamily: 'Lato Regular',
      fontWeight: 'normal',
      fontSize: '12px',
      lineHeight: '14px',
    },
    h6: {
      fontFamily: 'Lato Regular',
      fontWeight: 'normal',
      fontSize: '10px',
      lineHeight: '12px',
    },
    'body-normal': {
      fontFamily: 'Lato Regular',
      fontWeight: 'normal',
      fontSize: '14px',
      lineHeight: '16px',
    },
    'body-bold': {
      fontFamily: 'Lato Bold',
      fontWeight: 'normal',
      fontSize: '14px',
      lineHeight: '16px',
    },
    'number-xl': {
      fontFamily: 'Lato Light',
      fontWeight: 'normal',
      fontSize: '55px',
      lineHeight: '64px',
    },
    'number-l': {
      fontFamily: 'Lato Light',
      fontWeight: 'normal',
      fontSize: '40px',
      lineHeight: '50px',
    },
    'number-m': {
      fontFamily: 'Lato Light',
      fontWeight: 'normal',
      fontSize: '30px',
      lineHeight: '36px',
    },
    'number-s': {
      fontFamily: 'Lato Regular',
      fontWeight: 'normal',
      fontSize: '16px',
      lineHeight: '24px',
    },
  },
  font: {
    GangsterGroteskBold: 'Gangster Grotesk Bold',
    GangsterGroteskLight: 'Gangster Grotesk Light',
    GangsterGroteskRegular: 'Gangster Grotesk Regular',
    LatoBold: 'Lato Bold',
    LatoLight: 'Lato Light',
    LatoRegular: 'Lato Regular',
  },
};
